version: '3.8'

networks:
  parking-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:

# 开发环境服务
services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0.28
    container_name: parking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: parking_db
      MYSQL_USER: parking_admin
      MYSQL_PASSWORD: parking_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - parking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis缓存服务
  redis:
    image: redis:6.2.6
    container_name: parking-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - parking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 可选：管理工具服务
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: parking-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - parking-network
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: parking-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - parking-network
    depends_on:
      - redis

  # 应用服务
  app:
    build: .
    container_name: parking-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=parking_db
      - DB_USERNAME=parking_admin
      - DB_PASSWORD=parking_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - parking-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy