spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: ParkingHikariCP
  redis:
    host: localhost
    port: 6379
    timeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.parking.entity
amap:
  api-key: 0cbc240249d4b8cabab54b7f4ee81bdb

# 微信配置
wechat:
  appid: test_wechat_appid
  secret: test_wechat_secret_key
  mch_id: test_wechat_mch_id

# 支付配置
payment:
  wechat:
    appid: test_wechat_appid
    mchId: test_wechat_mch_id
  timeout: 1800000

# JWT配置
jwt:
  secret: test_jwt_secret_key
  expiration: 3600